# version : '3.7'
# services :
#   web:
#     build: .
#     ports:
#     - "8093:80"
#     volumes:
#       - ./config/nginx.conf:/etc/nginx/nginx.conf
#     restart: always
#   app1:
#     build: ./app1/
#     ports:
#     - "8085:80"
#     restart: always
#   app2:
#     build: ./app2
#     ports:
#     - "8010:80"
#     restart: always


version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    build: .
    environment:
      - VIRTUAL_HOST=deneme_com
    expose:
      - "80"  # Expose port 80 for the internal network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  app1:
    build: ./app1/
    expose:
      - "80"
    restart: always

  app2:
    build: ./app2
    expose:
      - "80"
    restart: always
