version: '3.7'
services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    expose:
      - 3000
    container_name: dbgate-instance
    volumes:
      - /home/kubilay/dbgate:/root/.dbgate
    environment:
      
      VIRTUAL_HOST: dbgate.local

      CONNECTIONS: con1,con2
      LABEL_con1: Postgres
      SERVER_con1: localhost
      USER_con1: postgres
      PASSWORD_con1: 12345
      PORT_con1: 32123
      ENGINE_con1: postgres@dbgate-plugin-postgres

      LABEL_con: MongoDB
      URL_con: mongodb://admin:12345@localhost:27017/deneme
      ENGINE_con: mongo@dbgate-plugin-mongo
    networks:
      - app-network-1
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - dbgate
    networks:
      - app-network-1
      
networks:
  app-network-1:
    driver: bridge
